services:
  backend:
    image: sandarsh/eil-backend:v1.3.0
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
    environment:
      PYTHONPATH: /app

  frontend:
    image: sandarsh/eil-frontend:v1.3.0
    ports:
      - "5173:5173"
    depends_on:
      - backend
